package ExceptionHandling;

public class Exceptions {
	
	
public static int divide(int a, int b) throws divideByZeroException {	// here we are passing a checked exception to the calling function, in this caise main
	if(b == 0) {
		throw new divideByZeroException();  
			
//		throw new ArithmeticException();
	}
	return a/b;
}
	

	public static void main(String[] args) {
		// 3 types of exceptions in java: 
//		Errors: 
//		Checked: expected exceptions
//		Unchecked: Unexpected exceptions
		
		
		try {
			divide(10,0);
		} catch (divideByZeroException error) {
			// TODO Auto-generated catch block
			error.printStackTrace();
		}
		
		
	}

}
